### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by vatterspun** [snemarch/fsekrit#1]
Could you list what you're licensing the code under?

Recommend going with something like the GPL or Apache license -- something that includes patent protections.

**Comment by snemarch** [comment]
I still haven't made up my mind, but it will probably be GPLv3 or Apache-2.0 - I'm leaning towards Apache, since fSekrit isn't a particularly big or revolutionary piece of software.

**Comment by vatterspun** [comment]
Cool, thanks for that. :+1:
